"""
PageController — 页面操作抽象

jobsdb/* 和 simulation/* 唯一依赖的页面接口。
收敛 v1.0 对 Playwright Page 的全部调用为有限方法集。

设计要点:
- Protocol 结构子类型:实现类无需显式继承,方法签名对上即可
- query_selector 返回 Playwright ElementHandle(类型标注),运行时假实现可返回 mock
- type_text 而非 type(避开 Python 内建名冲突)
- 便利方法 get_text/get_attribute/count/is_visible 收敛 v1.0 三行模式
"""

from typing import Any, Optional, Protocol

from playwright.async_api import ElementHandle


class PageController(Protocol):
    """页面操作抽象接口。"""

    # --- 导航 ---
    async def goto(self, url: str, wait_until: str = "domcontentloaded") -> None: ...
    @property
    def url(self) -> str: ...

    # --- 查询(只读) ---
    async def query_selector(self, selector: str) -> Optional[ElementHandle]: ...
    async def query_selector_all(self, selector: str) -> list: ...
    async def is_visible(self, selector: str) -> bool: ...
    async def count(self, selector: str) -> int: ...
    async def get_text(self, selector: str) -> Optional[str]: ...
    async def get_attribute(self, selector: str, attr: str) -> Optional[str]: ...

    # --- 交互(写) ---
    async def click(self, selector: str, timeout: float = 30.0) -> None: ...
    async def fill(self, selector: str, value: str) -> None: ...
    async def type_text(self, selector: str, value: str, delay: int = 50) -> None: ...
    async def select_option(self, selector: str, value: str) -> None: ...
    async def check(self, selector: str) -> None: ...

    # --- 等待 ---
    async def wait_for_selector(self, selector: str, timeout: float = 30.0) -> None: ...
    async def wait_for_timeout(self, ms: int) -> None: ...

    # --- JS 执行 ---
    async def evaluate(self, expression: str) -> Any: ...

    # --- 截图(异常诊断用) ---
    async def screenshot(self, path: str) -> None: ...
    def is_closed(self) -> bool: ...
